# Generated by Django 4.2.30 on 2026-05-19 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('draw_date', models.DateTimeField(auto_now_add=True, verbose_name='추첨 일시')),
                ('winning_numbers', models.CharField(blank=True, max_length=30, null=True, verbose_name='당첨 번호')),
                ('bonus_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='보너스 번호')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료 여부')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=30, verbose_name='선택 번호')),
                ('is_auto', models.BooleanField(default=False, verbose_name='자동 생성 여부')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='구매 일시')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='당첨 등수')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround', verbose_name='회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
        ),
    ]
